"""Initial layout

Revision ID: 0d18f3ceaace
Revises:
Create Date: 2022-07-06 19:41:49.299148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
from app.models.field_types import UTCDateTime

revision = '0d18f3ceaace'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codec_block_event',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('event_idx', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('event_module', sa.String(length=255), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('retry', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'event_idx')
    )
    op.create_index(op.f('ix_codec_block_event_block_hash'), 'codec_block_event', ['block_hash'], unique=False)
    op.create_index(op.f('ix_codec_block_event_block_number'), 'codec_block_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_codec_block_event_complete'), 'codec_block_event', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_block_event_event_idx'), 'codec_block_event', ['event_idx'], unique=False)
    op.create_index(op.f('ix_codec_block_event_event_module'), 'codec_block_event', ['event_module'], unique=False)
    op.create_index(op.f('ix_codec_block_event_event_name'), 'codec_block_event', ['event_name'], unique=False)
    op.create_index(op.f('ix_codec_block_event_extrinsic_idx'), 'codec_block_event', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_codec_block_event_retry'), 'codec_block_event', ['retry'], unique=False)
    op.create_table('codec_block_extrinsic',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('call_module', sa.String(length=255), nullable=True),
    sa.Column('call_name', sa.String(length=255), nullable=True),
    sa.Column('signed', sa.SmallInteger(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('retry', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'extrinsic_idx')
    )
    op.create_index(op.f('ix_codec_block_extrinsic_block_hash'), 'codec_block_extrinsic', ['block_hash'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_block_number'), 'codec_block_extrinsic', ['block_number'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_call_module'), 'codec_block_extrinsic', ['call_module'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_call_name'), 'codec_block_extrinsic', ['call_name'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_complete'), 'codec_block_extrinsic', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_extrinsic_idx'), 'codec_block_extrinsic', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_retry'), 'codec_block_extrinsic', ['retry'], unique=False)
    op.create_index(op.f('ix_codec_block_extrinsic_signed'), 'codec_block_extrinsic', ['signed'], unique=False)
    op.create_table('codec_block_header_digest_log',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('log_idx', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('retry', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'log_idx')
    )
    op.create_index(op.f('ix_codec_block_header_digest_log_block_hash'), 'codec_block_header_digest_log', ['block_hash'], unique=False)
    op.create_index(op.f('ix_codec_block_header_digest_log_block_number'), 'codec_block_header_digest_log', ['block_number'], unique=False)
    op.create_index(op.f('ix_codec_block_header_digest_log_complete'), 'codec_block_header_digest_log', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_block_header_digest_log_log_idx'), 'codec_block_header_digest_log', ['log_idx'], unique=False)
    op.create_index(op.f('ix_codec_block_header_digest_log_retry'), 'codec_block_header_digest_log', ['retry'], unique=False)
    op.create_table('codec_block_storage',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('storage_key', sa.VARBINARY(length=128), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('storage_module', sa.String(length=255), nullable=True),
    sa.Column('storage_name', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('retry', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'storage_key')
    )
    op.create_index(op.f('ix_codec_block_storage_block_hash'), 'codec_block_storage', ['block_hash'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_block_number'), 'codec_block_storage', ['block_number'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_complete'), 'codec_block_storage', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_retry'), 'codec_block_storage', ['retry'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_storage_key'), 'codec_block_storage', ['storage_key'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_storage_module'), 'codec_block_storage', ['storage_module'], unique=False)
    op.create_index(op.f('ix_codec_block_storage_storage_name'), 'codec_block_storage', ['storage_name'], unique=False)
    op.create_table('codec_block_timestamp',
    sa.Column('block_number', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('timestamp', mysql.NUMERIC(unsigned=True, precision=20, scale=0), nullable=True),
    sa.Column('datetime', UTCDateTime(timezone=True), nullable=True),
    sa.Column('year', mysql.INTEGER(display_width=4, unsigned=True), nullable=True),
    sa.Column('quarter', mysql.INTEGER(display_width=2, unsigned=True), nullable=True),
    sa.Column('month', mysql.INTEGER(display_width=4, unsigned=True), nullable=True),
    sa.Column('week', mysql.INTEGER(display_width=4, unsigned=True), nullable=True),
    sa.Column('day', mysql.INTEGER(display_width=4, unsigned=True), nullable=True),
    sa.Column('hour', mysql.INTEGER(display_width=4, unsigned=True), nullable=True),
    sa.Column('minute', mysql.INTEGER(display_width=4, unsigned=True), nullable=True),
    sa.Column('second', mysql.INTEGER(display_width=4, unsigned=True), nullable=True),
    sa.Column('full_quarter', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('full_month', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('full_week', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('full_day', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('full_hour', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('full_minute', mysql.NUMERIC(unsigned=True, precision=20, scale=0), nullable=True),
    sa.Column('full_second', mysql.NUMERIC(unsigned=True, precision=20, scale=0), nullable=True),
    sa.Column('weekday', mysql.INTEGER(display_width=4, unsigned=True), nullable=True),
    sa.Column('weekday_name', sa.String(length=16), nullable=True),
    sa.Column('month_name', sa.String(length=16), nullable=True),
    sa.Column('weekend', sa.Boolean(), nullable=True),
    sa.Column('range10000', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('range100000', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('range1000000', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('retry', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('block_number')
    )
    op.create_index(op.f('ix_codec_block_timestamp_block_hash'), 'codec_block_timestamp', ['block_hash'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_complete'), 'codec_block_timestamp', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_day'), 'codec_block_timestamp', ['day'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_full_day'), 'codec_block_timestamp', ['full_day'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_full_hour'), 'codec_block_timestamp', ['full_hour'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_full_minute'), 'codec_block_timestamp', ['full_minute'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_full_month'), 'codec_block_timestamp', ['full_month'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_full_quarter'), 'codec_block_timestamp', ['full_quarter'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_full_second'), 'codec_block_timestamp', ['full_second'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_full_week'), 'codec_block_timestamp', ['full_week'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_hour'), 'codec_block_timestamp', ['hour'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_minute'), 'codec_block_timestamp', ['minute'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_month'), 'codec_block_timestamp', ['month'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_quarter'), 'codec_block_timestamp', ['quarter'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_range10000'), 'codec_block_timestamp', ['range10000'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_range100000'), 'codec_block_timestamp', ['range100000'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_range1000000'), 'codec_block_timestamp', ['range1000000'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_retry'), 'codec_block_timestamp', ['retry'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_second'), 'codec_block_timestamp', ['second'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_timestamp'), 'codec_block_timestamp', ['timestamp'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_week'), 'codec_block_timestamp', ['week'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_weekday'), 'codec_block_timestamp', ['weekday'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_weekend'), 'codec_block_timestamp', ['weekend'], unique=False)
    op.create_index(op.f('ix_codec_block_timestamp_year'), 'codec_block_timestamp', ['year'], unique=False)
    op.create_table('codec_metadata',
    sa.Column('spec_name', sa.String(length=64), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('retry', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version')
    )
    op.create_index(op.f('ix_codec_metadata_complete'), 'codec_metadata', ['complete'], unique=False)
    op.create_index(op.f('ix_codec_metadata_retry'), 'codec_metadata', ['retry'], unique=False)
    op.create_index(op.f('ix_codec_metadata_spec_name'), 'codec_metadata', ['spec_name'], unique=False)
    op.create_index(op.f('ix_codec_metadata_spec_version'), 'codec_metadata', ['spec_version'], unique=False)
    op.create_table('harvester_status',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_harvester_status_key'), 'harvester_status', ['key'], unique=False)
    op.create_table('harvester_storage_cron',
    sa.Column('block_number_interval', sa.Integer(), nullable=False),
    sa.Column('storage_module', sa.String(length=255), nullable=False),
    sa.Column('storage_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.VARBINARY(length=128), nullable=True),
    sa.PrimaryKeyConstraint('block_number_interval', 'storage_module', 'storage_name')
    )
    op.create_index(op.f('ix_harvester_storage_cron_block_number_interval'), 'harvester_storage_cron', ['block_number_interval'], unique=False)
    op.create_index(op.f('ix_harvester_storage_cron_storage_module'), 'harvester_storage_cron', ['storage_module'], unique=False)
    op.create_index(op.f('ix_harvester_storage_cron_storage_name'), 'harvester_storage_cron', ['storage_name'], unique=False)
    op.create_table('harvester_storage_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.VARBINARY(length=128), nullable=True),
    sa.Column('storage_key_prefix', sa.VARBINARY(length=32), nullable=True),
    sa.Column('storage_pallet', sa.String(length=255), nullable=True),
    sa.Column('storage_name', sa.String(length=255), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvester_storage_task_complete'), 'harvester_storage_task', ['complete'], unique=False)
    op.create_table('node_block_extrinsic',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(length=4294967295), nullable=False),
    sa.Column('hash', sa.BINARY(length=32), nullable=False),
    sa.Column('length', sa.VARBINARY(length=5), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'extrinsic_idx')
    )
    op.create_index(op.f('ix_node_block_extrinsic_block_hash'), 'node_block_extrinsic', ['block_hash'], unique=False)
    op.create_index(op.f('ix_node_block_extrinsic_block_number'), 'node_block_extrinsic', ['block_number'], unique=False)
    op.create_index(op.f('ix_node_block_extrinsic_extrinsic_idx'), 'node_block_extrinsic', ['extrinsic_idx'], unique=False)
    op.create_table('node_block_header',
    sa.Column('hash', sa.BINARY(length=32), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('parent_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('number', sa.VARBINARY(length=5), nullable=False),
    sa.Column('extrinsics_root', sa.BINARY(length=32), nullable=False),
    sa.Column('state_root', sa.BINARY(length=32), nullable=False),
    sa.Column('count_extrinsics', sa.Integer(), server_default='0', nullable=False),
    sa.Column('count_logs', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_node_block_header_block_number'), 'node_block_header', ['block_number'], unique=False)
    op.create_table('node_block_header_digest_log',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('log_idx', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(length=4294967295), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'log_idx')
    )
    op.create_index(op.f('ix_node_block_header_digest_log_block_hash'), 'node_block_header_digest_log', ['block_hash'], unique=False)
    op.create_index(op.f('ix_node_block_header_digest_log_block_number'), 'node_block_header_digest_log', ['block_number'], unique=False)
    op.create_index(op.f('ix_node_block_header_digest_log_log_idx'), 'node_block_header_digest_log', ['log_idx'], unique=False)
    op.create_table('node_block_runtime',
    sa.Column('hash', sa.BINARY(length=32), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('spec_name', sa.String(length=32), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_node_block_runtime_block_number'), 'node_block_runtime', ['block_number'], unique=False)
    op.create_table('node_block_storage',
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('storage_key', sa.VARBINARY(length=128), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('storage_module', sa.String(length=255), nullable=True),
    sa.Column('storage_name', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('block_hash', 'storage_key')
    )
    op.create_index(op.f('ix_node_block_storage_block_hash'), 'node_block_storage', ['block_hash'], unique=False)
    op.create_index(op.f('ix_node_block_storage_block_number'), 'node_block_storage', ['block_number'], unique=False)
    op.create_index(op.f('ix_node_block_storage_complete'), 'node_block_storage', ['complete'], unique=False)
    op.create_index(op.f('ix_node_block_storage_storage_key'), 'node_block_storage', ['storage_key'], unique=False)
    op.create_index(op.f('ix_node_block_storage_storage_module'), 'node_block_storage', ['storage_module'], unique=False)
    op.create_index(op.f('ix_node_block_storage_storage_name'), 'node_block_storage', ['storage_name'], unique=False)
    op.create_table('node_metadata',
    sa.Column('spec_name', sa.String(length=64), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('data', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version')
    )
    op.create_index(op.f('ix_node_metadata_complete'), 'node_metadata', ['complete'], unique=False)
    op.create_index(op.f('ix_node_metadata_spec_name'), 'node_metadata', ['spec_name'], unique=False)
    op.create_index(op.f('ix_node_metadata_spec_version'), 'node_metadata', ['spec_version'], unique=False)
    op.create_table('node_runtime',
    sa.Column('impl_name', sa.String(length=64), nullable=False),
    sa.Column('impl_version', sa.Integer(), nullable=False),
    sa.Column('spec_name', sa.String(length=64), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('authoring_version', sa.Integer(), nullable=False),
    sa.Column('transaction_version', sa.Integer(), nullable=True),
    sa.Column('block_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('apis', sa.JSON(), nullable=True),
    sa.Column('code', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('impl_name', 'impl_version', 'spec_name', 'spec_version', 'authoring_version')
    )
    op.create_index(op.f('ix_node_runtime_authoring_version'), 'node_runtime', ['authoring_version'], unique=False)
    op.create_index(op.f('ix_node_runtime_complete'), 'node_runtime', ['complete'], unique=False)
    op.create_index(op.f('ix_node_runtime_impl_name'), 'node_runtime', ['impl_name'], unique=False)
    op.create_index(op.f('ix_node_runtime_impl_version'), 'node_runtime', ['impl_version'], unique=False)
    op.create_index(op.f('ix_node_runtime_spec_name'), 'node_runtime', ['spec_name'], unique=False)
    op.create_index(op.f('ix_node_runtime_spec_version'), 'node_runtime', ['spec_version'], unique=False)
    op.create_table('runtime',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('impl_name', sa.String(length=255), nullable=True),
    sa.Column('impl_version', sa.Integer(), nullable=True),
    sa.Column('authoring_version', sa.Integer(), nullable=True),
    sa.Column('count_call_functions', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.Column('count_pallets', sa.Integer(), nullable=False),
    sa.Column('count_storage_functions', sa.Integer(), nullable=False),
    sa.Column('count_constants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('count_errors', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version')
    )
    op.create_index(op.f('ix_runtime_spec_name'), 'runtime', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_spec_version'), 'runtime', ['spec_version'], unique=False)
    op.create_table('runtime_call',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('call_name', sa.String(length=255), nullable=False),
    sa.Column('pallet_call_idx', sa.Integer(), nullable=False),
    sa.Column('lookup', sa.BINARY(length=2), nullable=False),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('count_arguments', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'call_name')
    )
    op.create_index(op.f('ix_runtime_call_call_name'), 'runtime_call', ['call_name'], unique=False)
    op.create_index(op.f('ix_runtime_call_lookup'), 'runtime_call', ['lookup'], unique=False)
    op.create_index(op.f('ix_runtime_call_pallet'), 'runtime_call', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_call_spec_name'), 'runtime_call', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_call_spec_version'), 'runtime_call', ['spec_version'], unique=False)
    op.create_table('runtime_call_argument',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('call_name', sa.String(length=255), nullable=False),
    sa.Column('call_argument_idx', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('scale_type', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'call_name', 'call_argument_idx')
    )
    op.create_index(op.f('ix_runtime_call_argument_call_argument_idx'), 'runtime_call_argument', ['call_argument_idx'], unique=False)
    op.create_index(op.f('ix_runtime_call_argument_call_name'), 'runtime_call_argument', ['call_name'], unique=False)
    op.create_index(op.f('ix_runtime_call_argument_name'), 'runtime_call_argument', ['name'], unique=False)
    op.create_index(op.f('ix_runtime_call_argument_pallet'), 'runtime_call_argument', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_call_argument_spec_name'), 'runtime_call_argument', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_call_argument_spec_version'), 'runtime_call_argument', ['spec_version'], unique=False)
    op.create_table('runtime_constant',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('constant_name', sa.String(length=255), nullable=False),
    sa.Column('pallet_constant_idx', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=512), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'constant_name')
    )
    op.create_index(op.f('ix_runtime_constant_constant_name'), 'runtime_constant', ['constant_name'], unique=False)
    op.create_index(op.f('ix_runtime_constant_pallet'), 'runtime_constant', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_constant_pallet_constant_idx'), 'runtime_constant', ['pallet_constant_idx'], unique=False)
    op.create_index(op.f('ix_runtime_constant_spec_name'), 'runtime_constant', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_constant_spec_version'), 'runtime_constant', ['spec_version'], unique=False)
    op.create_table('runtime_error',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('error_name', sa.String(length=255), nullable=False),
    sa.Column('pallet_idx', sa.Integer(), nullable=False),
    sa.Column('error_idx', sa.Integer(), nullable=False),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'error_name')
    )
    op.create_index(op.f('ix_runtime_error_error_idx'), 'runtime_error', ['error_idx'], unique=False)
    op.create_index(op.f('ix_runtime_error_error_name'), 'runtime_error', ['error_name'], unique=False)
    op.create_index(op.f('ix_runtime_error_pallet'), 'runtime_error', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_error_pallet_idx'), 'runtime_error', ['pallet_idx'], unique=False)
    op.create_index(op.f('ix_runtime_error_spec_name'), 'runtime_error', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_error_spec_version'), 'runtime_error', ['spec_version'], unique=False)
    op.create_table('runtime_event',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('pallet_event_idx', sa.Integer(), nullable=False),
    sa.Column('lookup', sa.BINARY(length=2), nullable=False),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('count_attributes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'event_name')
    )
    op.create_index(op.f('ix_runtime_event_event_name'), 'runtime_event', ['event_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_lookup'), 'runtime_event', ['lookup'], unique=False)
    op.create_index(op.f('ix_runtime_event_pallet'), 'runtime_event', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_event_spec_name'), 'runtime_event', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_spec_version'), 'runtime_event', ['spec_version'], unique=False)
    op.create_table('runtime_event_attribute',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('event_attribute_idx', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'event_name', 'event_attribute_idx')
    )
    op.create_index(op.f('ix_runtime_event_attribute_event_attribute_idx'), 'runtime_event_attribute', ['event_attribute_idx'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_event_name'), 'runtime_event_attribute', ['event_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_pallet'), 'runtime_event_attribute', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_spec_name'), 'runtime_event_attribute', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_spec_version'), 'runtime_event_attribute', ['spec_version'], unique=False)
    op.create_table('runtime_pallet',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('count_call_functions', sa.Integer(), nullable=False),
    sa.Column('count_storage_functions', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.Column('count_constants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('count_errors', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet')
    )
    op.create_index(op.f('ix_runtime_pallet_pallet'), 'runtime_pallet', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_pallet_spec_name'), 'runtime_pallet', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_pallet_spec_version'), 'runtime_pallet', ['spec_version'], unique=False)
    op.create_table('runtime_storage',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('storage_name', sa.String(length=255), nullable=False),
    sa.Column('pallet_storage_idx', sa.Integer(), nullable=False),
    sa.Column('default', sa.BLOB(), nullable=True),
    sa.Column('modifier', sa.String(length=64), nullable=True),
    sa.Column('key_prefix_pallet', sa.BINARY(length=16), nullable=True),
    sa.Column('key_prefix_name', sa.BINARY(length=16), nullable=True),
    sa.Column('key1_scale_type', sa.String(length=512), nullable=True),
    sa.Column('key1_hasher', sa.String(length=255), nullable=True),
    sa.Column('key2_scale_type', sa.String(length=512), nullable=True),
    sa.Column('key2_hasher', sa.String(length=255), nullable=True),
    sa.Column('value_scale_type', sa.String(length=512), nullable=True),
    sa.Column('is_linked', sa.Boolean(), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'storage_name')
    )
    op.create_index(op.f('ix_runtime_storage_pallet'), 'runtime_storage', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_storage_spec_name'), 'runtime_storage', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_storage_spec_version'), 'runtime_storage', ['spec_version'], unique=False)
    op.create_index(op.f('ix_runtime_storage_storage_name'), 'runtime_storage', ['storage_name'], unique=False)
    op.create_table('runtime_type',
    sa.Column('spec_name', sa.String(length=255), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('scale_type', sa.String(length=512), nullable=False),
    sa.Column('decoder_class', sa.String(length=255), nullable=True),
    sa.Column('is_core_primitive', sa.Boolean(), nullable=True),
    sa.Column('is_runtime_primitive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'scale_type')
    )
    op.create_index(op.f('ix_runtime_type_scale_type'), 'runtime_type', ['scale_type'], unique=False)
    op.create_index(op.f('ix_runtime_type_spec_name'), 'runtime_type', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_type_spec_version'), 'runtime_type', ['spec_version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runtime_type_spec_version'), table_name='runtime_type')
    op.drop_index(op.f('ix_runtime_type_spec_name'), table_name='runtime_type')
    op.drop_index(op.f('ix_runtime_type_scale_type'), table_name='runtime_type')
    op.drop_table('runtime_type')
    op.drop_index(op.f('ix_runtime_storage_storage_name'), table_name='runtime_storage')
    op.drop_index(op.f('ix_runtime_storage_spec_version'), table_name='runtime_storage')
    op.drop_index(op.f('ix_runtime_storage_spec_name'), table_name='runtime_storage')
    op.drop_index(op.f('ix_runtime_storage_pallet'), table_name='runtime_storage')
    op.drop_table('runtime_storage')
    op.drop_index(op.f('ix_runtime_pallet_spec_version'), table_name='runtime_pallet')
    op.drop_index(op.f('ix_runtime_pallet_spec_name'), table_name='runtime_pallet')
    op.drop_index(op.f('ix_runtime_pallet_pallet'), table_name='runtime_pallet')
    op.drop_table('runtime_pallet')
    op.drop_index(op.f('ix_runtime_event_attribute_spec_version'), table_name='runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_attribute_spec_name'), table_name='runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_attribute_pallet'), table_name='runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_attribute_event_name'), table_name='runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_attribute_event_attribute_idx'), table_name='runtime_event_attribute')
    op.drop_table('runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_spec_version'), table_name='runtime_event')
    op.drop_index(op.f('ix_runtime_event_spec_name'), table_name='runtime_event')
    op.drop_index(op.f('ix_runtime_event_pallet'), table_name='runtime_event')
    op.drop_index(op.f('ix_runtime_event_lookup'), table_name='runtime_event')
    op.drop_index(op.f('ix_runtime_event_event_name'), table_name='runtime_event')
    op.drop_table('runtime_event')
    op.drop_index(op.f('ix_runtime_error_spec_version'), table_name='runtime_error')
    op.drop_index(op.f('ix_runtime_error_spec_name'), table_name='runtime_error')
    op.drop_index(op.f('ix_runtime_error_pallet_idx'), table_name='runtime_error')
    op.drop_index(op.f('ix_runtime_error_pallet'), table_name='runtime_error')
    op.drop_index(op.f('ix_runtime_error_error_name'), table_name='runtime_error')
    op.drop_index(op.f('ix_runtime_error_error_idx'), table_name='runtime_error')
    op.drop_table('runtime_error')
    op.drop_index(op.f('ix_runtime_constant_spec_version'), table_name='runtime_constant')
    op.drop_index(op.f('ix_runtime_constant_spec_name'), table_name='runtime_constant')
    op.drop_index(op.f('ix_runtime_constant_pallet_constant_idx'), table_name='runtime_constant')
    op.drop_index(op.f('ix_runtime_constant_pallet'), table_name='runtime_constant')
    op.drop_index(op.f('ix_runtime_constant_constant_name'), table_name='runtime_constant')
    op.drop_table('runtime_constant')
    op.drop_index(op.f('ix_runtime_call_argument_spec_version'), table_name='runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_argument_spec_name'), table_name='runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_argument_pallet'), table_name='runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_argument_name'), table_name='runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_argument_call_name'), table_name='runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_argument_call_argument_idx'), table_name='runtime_call_argument')
    op.drop_table('runtime_call_argument')
    op.drop_index(op.f('ix_runtime_call_spec_version'), table_name='runtime_call')
    op.drop_index(op.f('ix_runtime_call_spec_name'), table_name='runtime_call')
    op.drop_index(op.f('ix_runtime_call_pallet'), table_name='runtime_call')
    op.drop_index(op.f('ix_runtime_call_lookup'), table_name='runtime_call')
    op.drop_index(op.f('ix_runtime_call_call_name'), table_name='runtime_call')
    op.drop_table('runtime_call')
    op.drop_index(op.f('ix_runtime_spec_version'), table_name='runtime')
    op.drop_index(op.f('ix_runtime_spec_name'), table_name='runtime')
    op.drop_table('runtime')
    op.drop_index(op.f('ix_node_runtime_spec_version'), table_name='node_runtime')
    op.drop_index(op.f('ix_node_runtime_spec_name'), table_name='node_runtime')
    op.drop_index(op.f('ix_node_runtime_impl_version'), table_name='node_runtime')
    op.drop_index(op.f('ix_node_runtime_impl_name'), table_name='node_runtime')
    op.drop_index(op.f('ix_node_runtime_complete'), table_name='node_runtime')
    op.drop_index(op.f('ix_node_runtime_authoring_version'), table_name='node_runtime')
    op.drop_table('node_runtime')
    op.drop_index(op.f('ix_node_metadata_spec_version'), table_name='node_metadata')
    op.drop_index(op.f('ix_node_metadata_spec_name'), table_name='node_metadata')
    op.drop_index(op.f('ix_node_metadata_complete'), table_name='node_metadata')
    op.drop_table('node_metadata')
    op.drop_index(op.f('ix_node_block_storage_storage_name'), table_name='node_block_storage')
    op.drop_index(op.f('ix_node_block_storage_storage_module'), table_name='node_block_storage')
    op.drop_index(op.f('ix_node_block_storage_storage_key'), table_name='node_block_storage')
    op.drop_index(op.f('ix_node_block_storage_complete'), table_name='node_block_storage')
    op.drop_index(op.f('ix_node_block_storage_block_number'), table_name='node_block_storage')
    op.drop_index(op.f('ix_node_block_storage_block_hash'), table_name='node_block_storage')
    op.drop_table('node_block_storage')
    op.drop_index(op.f('ix_node_block_runtime_block_number'), table_name='node_block_runtime')
    op.drop_table('node_block_runtime')
    op.drop_index(op.f('ix_node_block_header_digest_log_log_idx'), table_name='node_block_header_digest_log')
    op.drop_index(op.f('ix_node_block_header_digest_log_block_number'), table_name='node_block_header_digest_log')
    op.drop_index(op.f('ix_node_block_header_digest_log_block_hash'), table_name='node_block_header_digest_log')
    op.drop_table('node_block_header_digest_log')
    op.drop_index(op.f('ix_node_block_header_block_number'), table_name='node_block_header')
    op.drop_table('node_block_header')
    op.drop_index(op.f('ix_node_block_extrinsic_extrinsic_idx'), table_name='node_block_extrinsic')
    op.drop_index(op.f('ix_node_block_extrinsic_block_number'), table_name='node_block_extrinsic')
    op.drop_index(op.f('ix_node_block_extrinsic_block_hash'), table_name='node_block_extrinsic')
    op.drop_table('node_block_extrinsic')
    op.drop_index(op.f('ix_harvester_storage_task_complete'), table_name='harvester_storage_task')
    op.drop_table('harvester_storage_task')
    op.drop_index(op.f('ix_harvester_storage_cron_storage_name'), table_name='harvester_storage_cron')
    op.drop_index(op.f('ix_harvester_storage_cron_storage_module'), table_name='harvester_storage_cron')
    op.drop_index(op.f('ix_harvester_storage_cron_block_number_interval'), table_name='harvester_storage_cron')
    op.drop_table('harvester_storage_cron')
    op.drop_index(op.f('ix_harvester_status_key'), table_name='harvester_status')
    op.drop_table('harvester_status')
    op.drop_index(op.f('ix_codec_metadata_spec_version'), table_name='codec_metadata')
    op.drop_index(op.f('ix_codec_metadata_spec_name'), table_name='codec_metadata')
    op.drop_index(op.f('ix_codec_metadata_retry'), table_name='codec_metadata')
    op.drop_index(op.f('ix_codec_metadata_complete'), table_name='codec_metadata')
    op.drop_table('codec_metadata')
    op.drop_index(op.f('ix_codec_block_timestamp_year'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_weekend'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_weekday'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_week'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_timestamp'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_second'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_retry'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_range1000000'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_range100000'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_range10000'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_quarter'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_month'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_minute'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_hour'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_full_week'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_full_second'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_full_quarter'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_full_month'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_full_minute'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_full_hour'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_full_day'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_day'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_complete'), table_name='codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_timestamp_block_hash'), table_name='codec_block_timestamp')
    op.drop_table('codec_block_timestamp')
    op.drop_index(op.f('ix_codec_block_storage_storage_name'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_storage_module'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_storage_key'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_retry'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_complete'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_block_number'), table_name='codec_block_storage')
    op.drop_index(op.f('ix_codec_block_storage_block_hash'), table_name='codec_block_storage')
    op.drop_table('codec_block_storage')
    op.drop_index(op.f('ix_codec_block_header_digest_log_retry'), table_name='codec_block_header_digest_log')
    op.drop_index(op.f('ix_codec_block_header_digest_log_log_idx'), table_name='codec_block_header_digest_log')
    op.drop_index(op.f('ix_codec_block_header_digest_log_complete'), table_name='codec_block_header_digest_log')
    op.drop_index(op.f('ix_codec_block_header_digest_log_block_number'), table_name='codec_block_header_digest_log')
    op.drop_index(op.f('ix_codec_block_header_digest_log_block_hash'), table_name='codec_block_header_digest_log')
    op.drop_table('codec_block_header_digest_log')
    op.drop_index(op.f('ix_codec_block_extrinsic_signed'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_retry'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_extrinsic_idx'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_complete'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_call_name'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_call_module'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_block_number'), table_name='codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_extrinsic_block_hash'), table_name='codec_block_extrinsic')
    op.drop_table('codec_block_extrinsic')
    op.drop_index(op.f('ix_codec_block_event_retry'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_extrinsic_idx'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_event_name'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_event_module'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_event_idx'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_complete'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_block_number'), table_name='codec_block_event')
    op.drop_index(op.f('ix_codec_block_event_block_hash'), table_name='codec_block_event')
    op.drop_table('codec_block_event')
    # ### end Alembic commands ###
