"""Add ID to harvester cron

Revision ID: 1be84ecb0e36
Revises: 861750430061
Create Date: 2022-07-20 17:37:18.125973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1be84ecb0e36'
down_revision = '861750430061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PRIMARY', 'harvester_storage_cron', type_='primary')
    op.execute("ALTER TABLE harvester_storage_cron ADD COLUMN id INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST")


    op.alter_column('harvester_storage_cron', 'block_number_interval',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('harvester_storage_cron', 'storage_module',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('harvester_storage_cron', 'storage_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_harvester_storage_cron_block_number_interval', table_name='harvester_storage_cron')
    op.drop_index('ix_harvester_storage_cron_storage_module', table_name='harvester_storage_cron')
    op.drop_index('ix_harvester_storage_cron_storage_name', table_name='harvester_storage_cron')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_harvester_storage_cron_storage_name', 'harvester_storage_cron', ['storage_name'], unique=False)
    op.create_index('ix_harvester_storage_cron_storage_module', 'harvester_storage_cron', ['storage_module'], unique=False)
    op.create_index('ix_harvester_storage_cron_block_number_interval', 'harvester_storage_cron', ['block_number_interval'], unique=False)
    op.alter_column('harvester_storage_cron', 'storage_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('harvester_storage_cron', 'storage_module',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('harvester_storage_cron', 'block_number_interval',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('PRIMARY', 'harvester_storage_cron', type_='primary')
    op.drop_column('harvester_storage_cron', 'id')
    op.create_primary_key('PRIMARY', 'harvester_storage_cron', ['block_number_interval', 'storage_module', 'storage_name'])
    # ### end Alembic commands ###
