"""Runtime block fields

Revision ID: 326f5803524b
Revises: 9e3a25bc0dc8
Create Date: 2022-11-25 13:29:11.125807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326f5803524b'
down_revision = '9e3a25bc0dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtime', sa.Column('block_hash', sa.BINARY(length=32), nullable=True))
    op.add_column('runtime', sa.Column('block_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runtime', 'block_number')
    op.drop_column('runtime', 'block_hash')
    # ### end Alembic commands ###
