"""Add storage key prefix to cron

Revision ID: 649f67b79c74
Revises: 1be84ecb0e36
Create Date: 2022-07-22 15:46:08.913856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649f67b79c74'
down_revision = '1be84ecb0e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harvester_storage_cron', sa.Column('storage_key_prefix', sa.VARBINARY(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harvester_storage_cron', 'storage_key_prefix')
    # ### end Alembic commands ###
