"""Event index account

Revision ID: 7fdd4370c1c6
Revises: 649f67b79c74
Create Date: 2022-10-18 11:36:46.990643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdd4370c1c6'
down_revision = '649f67b79c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codec_event_index_account',
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('event_idx', sa.Integer(), nullable=False),
    sa.Column('attribute_index', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.VARBINARY(length=33), nullable=False),
    sa.Column('pallet', sa.String(length=255), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('sort_value', sa.Integer(), nullable=True),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('block_number', 'event_idx', 'attribute_index')
    )
    op.create_index(op.f('ix_codec_event_index_account_account_id'), 'codec_event_index_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_codec_event_index_account_sort_value'), 'codec_event_index_account', ['sort_value'], unique=False)
    op.create_index('ix_codec_event_index_name_attr', 'codec_event_index_account', ['pallet', 'event_name', 'attribute_index'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_codec_event_index_name_attr', table_name='codec_event_index_account')
    op.drop_index(op.f('ix_codec_event_index_account_sort_value'), table_name='codec_event_index_account')
    op.drop_index(op.f('ix_codec_event_index_account_account_id'), table_name='codec_event_index_account')
    op.drop_table('codec_event_index_account')
    # ### end Alembic commands ###
