"""Add type composition fields

Revision ID: 84e857000376
Revises: 326f5803524b
Create Date: 2022-12-12 12:08:13.444622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e857000376'
down_revision = '326f5803524b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtime_call_argument', sa.Column('scale_type_composition', sa.JSON(), nullable=True))
    op.add_column('runtime_constant', sa.Column('scale_type_composition', sa.JSON(), nullable=True))
    op.add_column('runtime_event_attribute', sa.Column('scale_type_composition', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runtime_event_attribute', 'scale_type_composition')
    op.drop_column('runtime_constant', 'scale_type_composition')
    op.drop_column('runtime_call_argument', 'scale_type_composition')
    # ### end Alembic commands ###
