"""Runtime Event Attribute name

Revision ID: 9e3a25bc0dc8
Revises: e86ae2db09ca
Create Date: 2022-11-15 10:53:18.684746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3a25bc0dc8'
down_revision = 'e86ae2db09ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_event_attribute')
    op.create_table('runtime_event_attribute',
    sa.Column('spec_name', sa.String(length=64), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('pallet', sa.String(length=64), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_attribute_name', sa.String(length=64), nullable=False),
    sa.Column('scale_type', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'event_name', 'event_attribute_name')
    )
    op.create_index(op.f('ix_runtime_event_attribute_event_attribute_name'), 'runtime_event_attribute', ['event_attribute_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_event_name'), 'runtime_event_attribute', ['event_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_pallet'), 'runtime_event_attribute', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_spec_name'), 'runtime_event_attribute', ['spec_name'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_spec_version'), 'runtime_event_attribute', ['spec_version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_event_attribute')
    op.create_table('runtime_event_attribute',
                    sa.Column('spec_name', sa.String(length=255), nullable=False),
                    sa.Column('spec_version', sa.Integer(), nullable=False),
                    sa.Column('pallet', sa.String(length=255), nullable=False),
                    sa.Column('event_name', sa.String(length=255), nullable=False),
                    sa.Column('event_attribute_idx', sa.Integer(), nullable=False),
                    sa.Column('scale_type', sa.String(length=512), nullable=True),
                    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'pallet', 'event_name', 'event_attribute_idx')
                    )
    op.create_index(op.f('ix_runtime_event_attribute_event_attribute_idx'), 'runtime_event_attribute',
                    ['event_attribute_idx'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_event_name'), 'runtime_event_attribute', ['event_name'],
                    unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_pallet'), 'runtime_event_attribute', ['pallet'], unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_spec_name'), 'runtime_event_attribute', ['spec_name'],
                    unique=False)
    op.create_index(op.f('ix_runtime_event_attribute_spec_version'), 'runtime_event_attribute', ['spec_version'],
                    unique=False)
    # ### end Alembic commands ###
