"""Removed runtime_type table

Revision ID: e60f8742b969
Revises: 84e857000376
Create Date: 2022-12-12 12:25:38.278913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e60f8742b969'
down_revision = '84e857000376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_runtime_type_scale_type', table_name='runtime_type')
    op.drop_index('ix_runtime_type_spec_name', table_name='runtime_type')
    op.drop_index('ix_runtime_type_spec_version', table_name='runtime_type')
    op.drop_table('runtime_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_type',
    sa.Column('spec_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('spec_version', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scale_type', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('decoder_class', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_core_primitive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_runtime_primitive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('spec_name', 'spec_version', 'scale_type'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_runtime_type_spec_version', 'runtime_type', ['spec_version'], unique=False)
    op.create_index('ix_runtime_type_spec_name', 'runtime_type', ['spec_name'], unique=False)
    op.create_index('ix_runtime_type_scale_type', 'runtime_type', ['scale_type'], unique=False)
    # ### end Alembic commands ###
